"""dev-state-summary.md: the human handoff for the next session. Built only from the manifest's
non-secret fields, so it can be committed."""

from __future__ import annotations

from pathlib import Path


def _yn(v):
	return "yes" if v else "no"


def render(manifest: dict, published: dict | None) -> str:
	sid = manifest["snapshot_id"]
	lines = [
		"# Development state summary",
		"",
		"Generated by `save-dev-state.sh`. Contains no secrets. Code comes from Git; data comes from the snapshot.",
		"",
		f"- **Snapshot:** `{sid}`" + (f" ({manifest['label']})" if manifest.get("label") else ""),
		f"- **Saved at:** {manifest['created_at']} (UTC) on `{manifest.get('created_on_host')}`",
	]
	if published:
		if published.get("published"):
			enc = "encrypted (age)" if published.get("encrypted") else "UNENCRYPTED, local only"
			lines.append(f"- **Stored:** `{published['backend']}` backend, {enc}")
		elif published.get("blocked"):
			lines.append(f"- **Stored:** local only. {published['blocked']}")
		else:
			lines.append("- **Stored:** local snapshot directory only (not published)")
	lines += [
		"",
		"## Sites",
		"",
		"| Site | Database | Apps | Scheduler | developer_mode | mute_emails | Timezone | Country |",
		"|---|---|---|---|---|---|---|---|",
	]
	for s in manifest["sites"]:
		st = s["settings"]
		lines.append(
			f"| `{s['name']}` | {s['db']['db_type']} ({(s.get('db_server_version') or '?').split(' on ')[0]}) | {', '.join(s['installed_apps'])} | "
			f"{'ENABLED' if st.get('scheduler_enabled') else 'disabled'} | {_yn(st.get('developer_mode'))} | "
			f"{_yn(st.get('mute_emails'))} | {st.get('time_zone')} | {st.get('country')} |"
		)
	lines += [
		"",
		"## Repositories (code comes from these commits)",
		"",
		"| App | Branch | Commit | State | URL |",
		"|---|---|---|---|---|",
	]
	for r in manifest["repositories"]:
		state = "dirty" if r.get("dirty") else "clean"
		if r.get("unpushed_commits"):
			state += f", {r['unpushed_commits']} unpushed"
		lines.append(
			f"| `{r['app']}` | `{r.get('branch')}` | `{(r.get('commit') or '')[:12]}` | {state} | {r.get('url') or '-'} |"
		)
	t = manifest["tools"]
	lines += [
		"",
		"## Runtimes",
		"",
		f"Python {t.get('bench_python')} · Node {t.get('node')} · Yarn {t.get('yarn')} · Bench {t.get('bench')} · "
		f"pg_dump {t.get('pg_dump')} · MariaDB client {t.get('mariadb_client')} · Redis {t.get('redis_server')}",
		"",
		"## Safety state at save",
		"",
		f"- Schedulers enabled: {', '.join(s['name'] for s in manifest['sites'] if s['settings'].get('scheduler_enabled')) or 'none'}",
		f"- Background processes at save: {manifest.get('processes_at_save')}",
	]
	if manifest.get("warnings"):
		lines += ["", "## Warnings", ""] + [f"- {w}" for w in manifest["warnings"]]
	lines += [
		"",
		"## Restore in a new Claude Cloud session",
		"",
		"```bash",
		"cd /home/user/whatsapp_next/dev/cloud-state",
		"sudo ./bootstrap-cloud.sh                 # runtimes, services, bench, repositories (idempotent)",
		f"sudo ./restore-dev-state.sh {sid} --dry-run   # show the plan",
		f"sudo ./restore-dev-state.sh {sid} --yes       # add --force to replace sites that already exist",
		"sudo ./verify-dev-state.sh",
		"```",
		"",
	]
	return "\n".join(lines)


def write(path: Path, manifest: dict, published: dict | None):
	path.write_text(render(manifest, published))
