# Module role: meta assertions for the group-B DocTypes (fields.md RC-01) — every fieldname from
# plan/fields.md §7–9, §12–23 exists in the installed meta with the same fieldtype and Select options.

from __future__ import annotations

import frappe
from frappe.tests import IntegrationTestCase

CHILD_DOCTYPES = {
	"WhatsApp Contact Group Member",
	"WhatsApp Campaign Message",
	"WhatsApp Campaign Recipient",
	"WhatsApp Function Setting",
	"WhatsApp Function Output",
	"WhatsApp Command Party Type",
	"WhatsApp Notification Recipient",
	"WhatsApp Notification Alert Recipient",
}

# {doctype: [(fieldname, fieldtype, select_options_or_None), ...]}
EXPECTED: dict[str, list[tuple[str, str, list[str] | None]]] = {
	"WhatsApp Audit Log": [
		(
			"action",
			"Select",
			[
				"Device Created",
				"Device Connected",
				"Device Disconnected",
				"Device Deleted",
				"Credentials Changed",
				"Settings Changed",
				"Webhook Changed",
				"Connection Tested",
				"Queue Paused",
				"Queue Resumed",
				"Queue Rate Changed",
				"Queue Items Deleted",
				"Queue Items Retried",
				"Campaign Started",
				"Campaign Paused",
				"Campaign Resumed",
				"Campaign Cancelled",
				"Campaign Recipients Changed",
				"Contact Group Members Changed",
				"Bulk Send",
				"Test Send",
				"Elevated Contact Read",
				"Elevated Contact Write",
				"Number Linked",
				"Number Converted",
				"Conversation Confirmed",
				"Function Installed",
				"Function Updated",
				"Function Removed",
				"Command Changed",
				"Command Deleted",
				"Command Defaults Restored",
				"Retention Purge",
				"Alert Test Sent",
			],
		),
		("severity", "Select", ["Info", "Action", "Warning", "Danger"]),
		("summary", "Data", None),
		("user", "Link", None),
		("job_name", "Data", None),
		("timestamp", "Datetime", None),
		("reference_doctype", "Link", None),
		("reference_name", "Dynamic Link", None),
		("target_doctype", "Link", None),
		("target_name", "Dynamic Link", None),
		("fields_written", "Small Text", None),
		("reason", "Small Text", None),
		("count", "Int", None),
		("ip_address", "Data", None),
		("details", "JSON", None),
	],
	"WhatsApp Contact Group": [
		("group_name", "Data", None),
		("kind", "Select", ["Marketing", "Mailing List", "Professional", "Blacklist", "Other"]),
		("description", "Small Text", None),
		("source", "Select", ["Manual", "Import", "Picker"]),
		("member_count", "Int", None),
		("members_changed_at", "Datetime", None),
		("disabled", "Check", None),
		("members", "Table", None),
	],
	"WhatsApp Contact Group Member": [
		("phone", "Data", None),
		("phone_e164", "Data", None),
		("display_name", "Data", None),
		("contact", "Link", None),
		("source_type", "Select", ["Contact Group", "Contact", "DocType", "Excel", "vCard", "Manual"]),
		("source_doctype", "Link", None),
		("source_name", "Dynamic Link", None),
		("added_by", "Link", None),
		("added_on", "Datetime", None),
		("note", "Small Text", None),
	],
	"WhatsApp Campaign": [
		("campaign_name", "Data", None),
		("description", "Small Text", None),
		(
			"status",
			"Select",
			[
				"Draft",
				"Scheduled",
				"Queued",
				"Running",
				"Paused",
				"Completed",
				"Partially Failed",
				"Cancelled",
			],
		),
		("device", "Link", None),
		("scheduled_at", "Datetime", None),
		("messages_per_minute", "Int", None),
		("exclude_unknown_numbers", "Check", None),
		("messages", "Table", None),
		("recipients", "Table", None),
		("total_recipients", "Int", None),
		("initial_recipients", "Int", None),
		("added_count", "Int", None),
		("removed_count", "Int", None),
		("pause_count", "Int", None),
		("queued_count", "Int", None),
		("sent_count", "Int", None),
		("delivered_count", "Int", None),
		("read_count", "Int", None),
		("failed_count", "Int", None),
		("cancelled_count", "Int", None),
		("first_message_at", "Datetime", None),
		("last_message_at", "Datetime", None),
		("started_at", "Datetime", None),
		("ended_at", "Datetime", None),
		("last_batch_started_at", "Datetime", None),
		("started_by", "Link", None),
		("paused_at", "Datetime", None),
		("paused_by", "Link", None),
		("pause_reason", "Small Text", None),
		("cancelled_at", "Datetime", None),
		("cancelled_by", "Link", None),
		("cancel_reason", "Small Text", None),
	],
	"WhatsApp Campaign Message": [
		(
			"message_type",
			"Select",
			["Text", "Document", "Image", "Video", "Audio", "Sticker", "Location", "Poll"],
		),
		("template", "Link", None),
		("body", "Text", None),
		("caption", "Small Text", None),
		("attachment", "Attach", None),
		("print_format", "Link", None),
		("file_name_template", "Data", None),
		("poll_question", "Data", None),
		("poll_options", "JSON", None),
		("poll_allow_multiple", "Check", None),
		("delay_seconds", "Int", None),
	],
	"WhatsApp Campaign Recipient": [
		("recipient_type", "Select", ["Individual", "Group"]),
		("phone", "Data", None),
		("phone_e164", "Data", None),
		("jid", "Data", None),
		("display_name", "Data", None),
		("contact", "Link", None),
		("source_type", "Select", ["Contact Group", "Contact", "DocType", "Excel", "vCard", "Manual"]),
		("contact_group", "Link", None),
		("source_doctype", "Link", None),
		("source_name", "Dynamic Link", None),
		(
			"status",
			"Select",
			["Pending", "Queued", "Sent", "Delivered", "Read", "Failed", "Cancelled", "Removed"],
		),
		("outbound_message", "Link", None),
		("error_code", "Data", None),
		("added_by", "Link", None),
		("added_at", "Datetime", None),
		("removed_by", "Link", None),
		("removed_at", "Datetime", None),
	],
	"WhatsApp Function": [
		("function_key", "Data", None),
		("function_name", "Data", None),
		("category", "Data", None),
		("status", "Select", ["Active", "Inactive"]),
		("description", "Small Text", None),
		("when_to_use", "Small Text", None),
		("party_types", "Table MultiSelect", None),
		("installed_version", "Data", None),
		("installed_at", "Datetime", None),
		("installed_by", "Link", None),
		("latest_version", "Data", None),
		("latest_version_date", "Date", None),
		("update_available", "Check", None),
		("catalog_source", "Data", None),
		("catalog_checked_at", "Datetime", None),
		("checksum", "Data", None),
		("handler_registered", "Check", None),
		("manifest", "JSON", None),
		("settings", "Table", None),
		("outputs", "Table", None),
		("call_count", "Int", None),
		("last_called_at", "Datetime", None),
		("avg_ms", "Int", None),
		("error_count", "Int", None),
		("last_error", "Small Text", None),
	],
	"WhatsApp Function Setting": [
		("key", "Data", None),
		("label", "Data", None),
		("fieldtype", "Select", ["Check", "Int", "Data", "Select"]),
		("choices", "Small Text", None),
		("default_value", "Data", None),
		("value", "Data", None),
		("notes", "Small Text", None),
	],
	"WhatsApp Function Output": [
		("output_key", "Data", None),
		("label", "Data", None),
		("output_type", "Select", ["Text", "Document"]),
		("default_template", "Text", None),
		("template", "Text", None),
		("condition", "Code", None),
		("print_format", "Link", None),
		("file_name_template", "Data", None),
		("variables", "Small Text", None),
		("notes", "Small Text", None),
	],
	"WhatsApp Command": [
		("code", "Data", None),
		("title", "Data", None),
		("function", "Link", None),
		("status", "Select", ["Active", "Inactive"]),
		("synonyms", "Small Text", None),
		("requires_linked_contact", "Check", None),
		("allowed_party_types", "Table MultiSelect", None),
		("allowed_group", "Link", None),
		("blocked_group", "Link", None),
		("reply_device", "Link", None),
		("settings_overrides", "JSON", None),
		("outputs", "Table", None),
		("description", "Small Text", None),
		("run_count", "Int", None),
		("last_run_at", "Datetime", None),
		("defaults_restored_at", "Datetime", None),
	],
	"WhatsApp Command Party Type": [
		("party_type", "Link", None),
	],
	"WhatsApp Notification": [
		("notification_name", "Data", None),
		("enabled", "Check", None),
		("document_type", "Link", None),
		(
			"event",
			"Select",
			[
				"New",
				"Save",
				"Submit",
				"Cancel",
				"Days Before",
				"Days After",
				"Minutes Before",
				"Minutes After",
				"Value Change",
				"Method",
			],
		),
		("date_changed", "Select", None),
		("days_in_advance", "Int", None),
		("datetime_changed", "Select", None),
		("minutes_offset", "Int", None),
		("value_changed", "Select", None),
		("method", "Data", None),
		("condition", "Code", None),
		("device", "Link", None),
		("template", "Link", None),
		("message", "Code", None),
		("message_type", "Select", ["Text", "Document", "Image"]),
		("attach_print", "Check", None),
		("print_format", "Link", None),
		("letter_head", "Link", None),
		("attach_field", "Data", None),
		("recipients", "Table", None),
		("set_property_after_alert", "Select", None),
		("property_value", "Data", None),
		("variables_count", "Int", None),
		("send_count", "Int", None),
		("last_sent_at", "Datetime", None),
		("last_error", "Small Text", None),
		("last_error_at", "Datetime", None),
	],
	"WhatsApp Notification Recipient": [
		("recipient_type", "Select", ["Document Field", "Linked Document Field", "Fixed Number"]),
		("receiver_by_document_field", "Select", None),
		("linked_document_field", "Select", None),
		("linked_mobile_fieldname", "Data", None),
		("phone", "Data", None),
		("phone_e164", "Data", None),
		("condition", "Code", None),
	],
	"WhatsApp Notification Alert": [
		("alert_name", "Data", None),
		("enabled", "Check", None),
		("periodicity", "Select", ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly"]),
		(
			"day_of_week",
			"Select",
			["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
		),
		("day_of_month", "Int", None),
		(
			"month_of_year",
			"Select",
			[
				"January",
				"February",
				"March",
				"April",
				"May",
				"June",
				"July",
				"August",
				"September",
				"October",
				"November",
				"December",
			],
		),
		("notification_time", "Time", None),
		("content_type", "Select", ["Report", "Static Message"]),
		("report", "Link", None),
		("filters_json", "Code", None),
		("dynamic_filters_json", "Code", None),
		("template", "Link", None),
		("message", "Code", None),
		("attachment_format", "Select", ["None", "PDF", "PNG"]),
		("print_format", "Link", None),
		("letter_head", "Link", None),
		("language", "Link", None),
		("device", "Link", None),
		("recipients", "Table", None),
		("send_count", "Int", None),
		("last_sent_at", "Datetime", None),
		("next_run_at", "Datetime", None),
		("last_error", "Small Text", None),
	],
	"WhatsApp Notification Alert Recipient": [
		("recipient_type", "Select", ["User", "Role", "Phone", "Report Column"]),
		("user", "Link", None),
		("role", "Link", None),
		("phone", "Data", None),
		("phone_e164", "Data", None),
		("report_column", "Data", None),
	],
}


class TestFieldsGroupB(IntegrationTestCase):
	"""Every planned field is installed with the planned type and options."""

	def test_fields_installed(self) -> None:
		for doctype, rows in EXPECTED.items():
			meta = frappe.get_meta(doctype)
			for fieldname, fieldtype, options in rows:
				with self.subTest(doctype=doctype, field=fieldname):
					df = meta.get_field(fieldname)
					self.assertIsNotNone(df, f"{doctype}.{fieldname} missing")
					self.assertEqual(df.fieldtype, fieldtype)
					if options is not None:
						self.assertEqual((df.options or "").split("\n"), options)

	def test_children_are_tables(self) -> None:
		for doctype in EXPECTED:
			meta = frappe.get_meta(doctype)
			self.assertEqual(bool(meta.istable), doctype in CHILD_DOCTYPES, doctype)

	def test_module_and_naming(self) -> None:
		for doctype in EXPECTED:
			meta = frappe.get_meta(doctype)
			self.assertEqual(meta.module, "WhatsApp Next", doctype)
			if doctype in CHILD_DOCTYPES:
				self.assertEqual(meta.permissions, [], doctype)
		self.assertEqual(frappe.get_meta("WhatsApp Audit Log").in_create, 1)
		self.assertEqual(frappe.get_meta("WhatsApp Campaign").autoname, "WA-CAMP-.YYYY.-.#####")
		self.assertEqual(frappe.get_meta("WhatsApp Command").autoname, "field:code")
